version: '3.8'

services:
  mongodb:
    image: docker.io/mongo:latest
    container_name: restaurant-mongodb
    network_mode: host
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  app:
    build: .
    container_name: restaurant-app
    network_mode: host
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://root:example@127.0.0.1:27017/restaurant?authSource=admin&directConnection=true
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongodb_data:
