version: '3.8'

services:
  mongodb:
    image: docker.io/mongo:latest
    container_name: restaurant-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  app:
    build: .
    container_name: restaurant-app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://root:example@mongodb:27017/restaurant?authSource=admin
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongodb_data:
